spring:
  application:
    name: cyber-done-device-microservice
    version: @version@
  profiles:
    active: dev
  datasource:
    username: postgres
    password: ${CDDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true